function I = impact(CI,F,P)

% Parameters

e = P.restitution ;
r = P.rayon ;
X = CI ;
Vlimite = P.Vlimite;

% creation of a local orthonormal base at a point of impact of the surface

nz= normale(X(1),X(2),F) ;                  % local base z axis {n}
nx = [-nz(3),0,nz(1)];                      % x axis of the local base {n} orthogonal to the previous one
ny = cross(nz,nx);                          % y-axis generated by product
nx = nx./norm(nx)  ;                        % normalization of {n}
ny = ny./norm(ny);
Mat_n_e = [nx',ny',nz'];                    % Matrix of basis {n} in {e}

% velocity in {n} - reflection

V = [X(4),X(5),X(6)]' ;                     % velocity
Vn = Mat_n_e\V   ;                          % O velocity in the base of the tangent plane
Vn(3) = -e*Vn(3) ;                          

% condition for stopping or not bouncing

if Vn(3) < Vlimite
    rebond = 0 ;
    Vn(3) = 0 ;   
else
    rebond = 1 ;
end

% passage of the results in the fixed cartesian base of work

Ve = Mat_n_e*Vn ;                         
X(4) = Ve(1) ;
X(5) = Ve(2) ;
X(6) = Ve(3) ;

I = [X,rebond];